

global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
scrape_configs:
  - job_name: 'otel'
    scrape_interval: 10s
    static_configs:
      # - targets: ['otel:8889']
      - targets: ['otel:8888']
  - job_name: 'traefik'
    static_configs:
      - targets:
          - "traefik:8082"