---
services:
  pgadmin:
    image: dpage/pgadmin4
    ports: [5434:80]
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    volumes:
      - .docker-cache/pgadmin/servers.jso:/pgadmin4/servers.json:delegated
