
services:
  postgres:
    profiles:
      - all
    image: postgres:latest
    restart: always
    command: postgres -c "max-connections=10"

    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=main
      - POSTGRES_USER=main
      - POSTGRES_DB_MAIN=main
      - POSTGRES_ROOT_PASSWORD=main
    volumes:
      - .docker-cache/pg:/var/lib/postgresql/data:delegated
      - ./db/initdb.d/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U main -d main"]
      interval: 5s

  # # cache db
  # redis:
  #   profiles:
  #     - all
  #   image: redis:3.2
  #   command: ["redis-server", "--appendonly", "yes"]
  #   healthcheck:
  #     test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
  #     interval: 1s
  #     timeout: 3s
  #     retries: 5
